"""
streamlit_app.py — Web interface for the 元吾氏 AI 助教 (Claude + semantic RAG).

Each browser session gets its own independent chat history.
Requires teacher_files.json + teacher_embeddings.npy (generated by: python3 agent.py --build).
"""

import json
import os
import datetime
import numpy as np
import faiss
import anthropic
import streamlit as st
from sentence_transformers import SentenceTransformer

FILES_DB = "teacher_files.json"
EMBEDDINGS_DB = "teacher_embeddings.npy"
FEEDBACK_LOG = "feedback_log.jsonl"
TEACHER_NAME = "元吾氏"
MODEL = "claude-sonnet-4-6"
EMBED_MODEL = "paraphrase-multilingual-MiniLM-L12-v2"
TOP_K = 8
MAX_HISTORY_TURNS = 10
MIN_RETRIEVAL_SCORE = 0.3


def build_system_instruction(state: dict) -> str:
    teacher_name = state.get("teacher_name", TEACHER_NAME)
    return f"""你是{teacher_name}老师的AI助教，熟悉老师的整套教学体系，帮助学生理解和消化老师的教学内容。

【核心原则】
1. 以提供的「老师材料」为依据来回答问题。用自己的语言自然地讲解、归纳和总结，不需要逐字引用，但内容必须忠实于老师的原意。
2. 如果材料中确实找不到相关内容，直接告诉学生："这个问题在老师现有的材料中没有找到，建议直接向老师请教。" 不要编造。
3. 来源引用灵活处理：当内容来自某本书或某篇文章时，自然地提一下出处即可（如"老师在意识强度一书中提到……"），不必每句话都标注。
4. 讲解时可以有教学温度——适当引导学生思考、帮助他们建立概念之间的联系，但不做主观价值判断，不替学生下结论。
5. 严禁混入任何宗教内容、宗教术语或宗教类比（佛教、道教、基督教、伊斯兰教等），老师的体系是独立的，不与任何宗教挂钩。
6. 不要把其他思想体系、哲学流派或心理学理论混入老师的观点中，保持老师体系的纯粹性。"""


@st.cache_resource(show_spinner="正在加载知识库和语义检索模型…")
def load_resources():
    """Load chunks, embeddings, build FAISS index. Runs once per instance."""
    with open(FILES_DB, encoding="utf-8") as f:
        state = json.load(f)
    chunks = state.get("chunks", [])

    embeddings = np.load(EMBEDDINGS_DB).astype(np.float32)
    dim = embeddings.shape[1]
    index = faiss.IndexFlatIP(dim)
    index.add(embeddings)

    embed_model = SentenceTransformer(EMBED_MODEL)
    client = anthropic.Anthropic(api_key=os.environ.get("ANTHROPIC_API_KEY"))
    system_instruction = build_system_instruction(state)

    return state, client, system_instruction, chunks, index, embed_model


def retrieve_context(
    query: str,
    history: list,
    chunks: list,
    index: faiss.IndexFlatIP,
    embed_model: SentenceTransformer,
) -> tuple[str, bool]:
    recent_user_qs = " ".join(
        msg["content"] for msg in history[-4:]
        if msg.get("role") == "user" and isinstance(msg["content"], str)
    )
    search_text = (query + " " + recent_user_qs).strip()
    query_vec = embed_model.encode([search_text], normalize_embeddings=True).astype(np.float32)
    scores, indices = index.search(query_vec, TOP_K)

    relevant = [
        (score, idx)
        for score, idx in zip(scores[0], indices[0])
        if score >= MIN_RETRIEVAL_SCORE and idx >= 0
    ]
    if not relevant:
        return "", False

    parts = [f"[来源: {chunks[idx]['source']}]\n{chunks[idx]['text']}" for _, idx in relevant]
    return "\n\n---\n\n".join(parts), True


def build_augmented_message(query: str, history: list, chunks: list, index, embed_model) -> str:
    context, has_content = retrieve_context(query, history, chunks, index, embed_model)
    if has_content:
        return f"以下是老师材料中可能相关的内容：\n\n{context}\n\n---\n\n学生问题：{query}"
    return (
        "【系统提示：在知识库中未检索到与此问题相关的内容。"
        "请告知学生此问题超出你所掌握的老师材料范围。】\n\n"
        f"学生问题：{query}"
    )


def log_feedback(question: str, answer: str, rating: str, comment: str = ""):
    entry = {
        "timestamp": datetime.datetime.now().isoformat(),
        "question": question,
        "answer": answer,
        "rating": rating,
        "comment": comment,
    }
    with open(FEEDBACK_LOG, "a", encoding="utf-8") as f:
        f.write(json.dumps(entry, ensure_ascii=False) + "\n")


def _render_feedback_row(msg: dict):
    """Render 👍 👎 buttons for one assistant message. Uses msg content as unique key."""
    fkey = str(hash(msg["content"]))
    if fkey in st.session_state.feedback_done:
        st.caption("✅ 已收到反馈，谢谢！")
        return

    col1, col2, col3 = st.columns([1, 1, 8])
    if col1.button("👍", key=f"good_{fkey}"):
        log_feedback(msg.get("question", ""), msg["content"], "good")
        st.session_state.feedback_done.add(fkey)
        st.rerun()
    if col2.button("👎", key=f"bad_{fkey}"):
        st.session_state[f"show_comment_{fkey}"] = True
        st.rerun()

    if st.session_state.get(f"show_comment_{fkey}"):
        comment = st.text_input("请简述问题所在（可选）：", key=f"comment_{fkey}")
        if st.button("提交", key=f"submit_{fkey}"):
            log_feedback(msg.get("question", ""), msg["content"], "bad", comment)
            st.session_state.feedback_done.add(fkey)
            st.session_state.pop(f"show_comment_{fkey}", None)
            st.rerun()


def stream_response(client: anthropic.Anthropic, system_instruction: str, api_messages: list):
    with client.messages.stream(
        model=MODEL,
        max_tokens=2048,
        system=system_instruction,
        messages=api_messages,
    ) as stream:
        for text in stream.text_stream:
            yield text


def main():
    st.set_page_config(page_title="元吾氏 AI助教", page_icon="📚")
    st.title("📚 元吾氏 AI助教")

    state, client, system_instruction, chunks, index, embed_model = load_resources()
    st.caption(f"知识库：{len(chunks)} 个文本块 · 语义检索（中英文）")

    if "history" not in st.session_state:
        st.session_state.history = []
        st.session_state.messages = []   # {role, content, question?}
        st.session_state.feedback_done = set()

    # Render full chat history
    for msg in st.session_state.messages:
        with st.chat_message(msg["role"]):
            st.markdown(msg["content"])
        # Show feedback buttons for past assistant messages
        if msg["role"] == "assistant":
            _render_feedback_row(msg)

    user_input = st.chat_input("请输入你的问题…")
    if not user_input:
        return

    st.session_state.messages.append({"role": "user", "content": user_input})
    with st.chat_message("user"):
        st.markdown(user_input)

    augmented = build_augmented_message(
        user_input, st.session_state.history, chunks, index, embed_model
    )
    trimmed_history = st.session_state.history[-(MAX_HISTORY_TURNS * 2):]
    api_messages = trimmed_history + [{"role": "user", "content": augmented}]

    with st.chat_message("assistant"):
        try:
            response_text = st.write_stream(
                stream_response(client, system_instruction, api_messages)
            )
        except Exception as e:
            st.error(f"出错了：{e}")
            st.session_state.messages.pop()
            return

    new_msg = {"role": "assistant", "content": response_text, "question": user_input}
    st.session_state.messages.append(new_msg)
    st.session_state.history.append({"role": "user", "content": user_input})
    st.session_state.history.append({"role": "assistant", "content": response_text})

    # Show feedback buttons immediately after streaming (same render cycle)
    _render_feedback_row(new_msg)


if __name__ == "__main__":
    main()
