"""
streamlit_app.py — Web interface for the 元吾氏 AI 助教 (Gemini + BM25 RAG).

Each browser session gets its own independent chat history.
Requires teacher_files.json to be present (generated by running agent.py locally first).
"""

import json
import os
import jieba
from rank_bm25 import BM25Okapi
import streamlit as st
from google import genai
from google.genai import types

FILES_DB = "teacher_files.json"
TEACHER_NAME = "元吾氏"
MODEL = "gemini-2.5-flash"
TOP_K = 8
MAX_HISTORY_TURNS = 10  # keep last N turns in API history


def build_system_instruction(state: dict) -> str:
    teacher_name = state.get("teacher_name", TEACHER_NAME)
    return f"""你就是{teacher_name}本人。有人在跟你聊天请教，你要完全以本人的身份、口吻和视角来回答，就像跟老朋友聊天一样自然随意。

角色要求：
- 用第一人称"我"，语气轻松，像朋友聊天，不要有说教感
- 不要表现出你是AI
- 根据你的教学内容和想法来回答，有自己的态度和观点
- 如果问到你不确定的，可以直接说"我也没想太清楚"或者聊聊你的感受
- 优先用中文回答，除非对方用其他语言
- 可以反问，帮对方自己想清楚，不用每次都给完整答案
- 不要说"根据材料""文档中提到"这类话，直接说你的想法就好

回答风格：
- 简明扼要，不废话
- 用要点、次点、编号（一、二、三或1. 2. 3.）把内容分层说清楚
- 能用三句话说完就不用五句话"""


@st.cache_resource
def load_resources():
    """Load state, build BM25 index, and init Gemini client. Runs once per instance."""
    client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY"))

    with open(FILES_DB, encoding="utf-8") as f:
        state = json.load(f)

    chunks = state.get("chunks", [])
    corpus = [list(jieba.cut(c["text"])) for c in chunks]
    bm25 = BM25Okapi(corpus)

    system_instruction = build_system_instruction(state)
    return state, client, system_instruction, chunks, bm25


def retrieve_context(query: str, history: list, chunks: list[dict], bm25: BM25Okapi) -> str:
    # Combine current query with last 2 assistant turns for better follow-up retrieval
    recent = " ".join(
        part["text"]
        for msg in history[-4:]
        for part in msg.get("parts", [])
    )
    search_text = query + " " + recent
    query_tokens = list(jieba.cut(search_text))
    scores = bm25.get_scores(query_tokens)
    top_indices = sorted(range(len(scores)), key=lambda i: scores[i], reverse=True)[:TOP_K]
    parts = [f"[{chunks[i]['source']}]\n{chunks[i]['text']}" for i in top_indices]
    return "\n\n---\n\n".join(parts)


def response_stream(client, system_instruction: str, api_messages: list):
    stream = client.models.generate_content_stream(
        model=MODEL,
        contents=api_messages,
        config=types.GenerateContentConfig(
            system_instruction=system_instruction,
        ),
    )
    for chunk in stream:
        if chunk.text:
            yield chunk.text


def main():
    st.set_page_config(page_title="元吾氏 AI助教", page_icon="📚")
    st.title("📚 元吾氏 AI助教")

    with st.spinner("正在加载知识库…"):
        state, client, system_instruction, chunks, bm25 = load_resources()
    st.caption(f"知识库：{len(chunks)} 个文本块，每次检索最相关的 {TOP_K} 块")

    # Per-session state
    if "history" not in st.session_state:
        st.session_state.history = []   # original messages for API multi-turn
        st.session_state.messages = []  # display messages

    # Render chat history
    for msg in st.session_state.messages:
        with st.chat_message(msg["role"]):
            st.markdown(msg["content"])

    user_input = st.chat_input("请输入你的问题…")
    if not user_input:
        return

    st.session_state.messages.append({"role": "user", "content": user_input})
    with st.chat_message("user"):
        st.markdown(user_input)

    # Retrieve relevant chunks (using query + recent history for follow-up awareness)
    context = retrieve_context(user_input, st.session_state.history, chunks, bm25)
    augmented = f"以下是可能相关的参考内容：\n\n{context}\n\n---\n\n问题：{user_input}"

    # Trim history to last N turns to prevent unbounded growth
    trimmed_history = st.session_state.history[-(MAX_HISTORY_TURNS * 2):]
    api_messages = trimmed_history + [{"role": "user", "parts": [{"text": augmented}]}]

    with st.chat_message("assistant"):
        try:
            response_text = st.write_stream(
                response_stream(client, system_instruction, api_messages)
            )
        except Exception as e:
            st.error(f"出错了：{e}")
            st.session_state.messages.pop()
            return

    # Store original (unaugmented) message in history
    st.session_state.messages.append({"role": "assistant", "content": response_text})
    st.session_state.history.append({"role": "user", "parts": [{"text": user_input}]})
    st.session_state.history.append({"role": "model", "parts": [{"text": response_text}]})


if __name__ == "__main__":
    main()
