"""
streamlit_app.py — Web interface for the 元吾氏 AI 助教.

Each browser session gets its own independent chat history.
Requires teacher_files.json to be present (generated by running agent.py locally first).

Deploy to Streamlit Community Cloud:
    1. Push this repo to GitHub
    2. Go to share.streamlit.io and connect the repo
    3. Set ANTHROPIC_API_KEY in the app secrets
"""

import json
import streamlit as st
import anthropic

FILES_DB = "teacher_files.json"
TEACHER_NAME = "元吾氏"
MAX_PAGE_TEXT_CHARS = 3000
MAX_PAGES_IN_CONTEXT = 30


@st.cache_resource
def load_resources():
    """Load state and build shared resources once for all users."""
    with open(FILES_DB, encoding="utf-8") as f:
        state = json.load(f)

    client = anthropic.Anthropic()
    system_blocks = _build_system_prompt(state)
    doc_blocks = _build_doc_blocks(state)
    return state, client, system_blocks, doc_blocks


def _build_system_prompt(state: dict) -> list[dict]:
    teacher_name = state.get("teacher_name", TEACHER_NAME)
    website_url = state.get("website_url", "")
    page_texts: list[dict] = state.get("page_texts", [])

    intro = f"""你就是{teacher_name}老师本人。学生正在向你请教问题，你要完全以老师本人的身份、口吻和视角来回答，就像在课堂上或办公室里亲自辅导学生一样。

角色要求：
- 用第一人称"我"来表达，比如"我在课上讲过……""我的意思是……""你可以翻翻我给你们的讲义第X页"
- 保持老师本人的语气和风格，不要表现出你是AI
- 根据课程材料（PDF讲义、课程网站）来回答，这些都是你自己准备的教学内容
- 如果学生问到材料之外的内容，以老师的口吻引导或给出你的判断
- 优先用中文回答，除非学生用其他语言提问
- 可以适当反问学生，帮助他们自己思考，而不只是直接给答案
- 不要说"根据材料""文档中提到"这类话——那是你自己写的内容，直接讲就好"""

    blocks: list[dict] = [{"type": "text", "text": intro}]

    if page_texts:
        pages_block = f"\n\n## 课程网站内容（来源: {website_url}）\n\n"
        for page in page_texts[:MAX_PAGES_IN_CONTEXT]:
            title = page.get("title", page["url"])
            text = page["text"][:MAX_PAGE_TEXT_CHARS]
            pages_block += f"### {title}\n{text}\n\n"
        blocks.append({
            "type": "text",
            "text": pages_block,
            "cache_control": {"type": "ephemeral"},
        })

    return blocks


def _build_doc_blocks(state: dict) -> list[dict]:
    return [
        {
            "type": "document",
            "source": {"type": "file", "file_id": info["file_id"]},
            "title": info["filename"],
        }
        for info in state.get("file_ids", {}).values()
    ]


def response_stream(client, system_blocks, messages):
    """Generator that yields text chunks from the Anthropic streaming API."""
    with client.beta.messages.stream(
        model="claude-opus-4-6",
        max_tokens=2048,
        system=system_blocks,
        messages=messages,
        betas=["files-api-2025-04-14"],
    ) as stream:
        for text in stream.text_stream:
            yield text


def main():
    st.set_page_config(page_title="元吾氏 AI助教", page_icon="📚")
    st.title("📚 元吾氏老师 AI助教")

    state, client, system_blocks, doc_blocks = load_resources()
    pdf_count = len(state.get("file_ids", {}))
    page_count = len(state.get("page_texts", []))
    st.caption(f"已加载 {pdf_count} 份讲义 + {page_count} 个课程网页")

    # Per-session state
    if "messages" not in st.session_state:
        st.session_state.messages = []
        st.session_state.docs_injected = False

    # Render chat history (extract display text from first-turn content blocks)
    for msg in st.session_state.messages:
        role = msg["role"]
        content = msg["content"]
        display_text = (
            content if isinstance(content, str)
            else next((b["text"] for b in content if b.get("type") == "text"), "")
        )
        with st.chat_message("user" if role == "user" else "assistant"):
            st.markdown(display_text)

    # Input
    user_input = st.chat_input("请输入你的问题…")
    if not user_input:
        return

    # First turn: prepend PDF document blocks
    if not st.session_state.docs_injected:
        content = doc_blocks + [{"type": "text", "text": user_input}]
        st.session_state.docs_injected = True
    else:
        content = user_input

    st.session_state.messages.append({"role": "user", "content": content})
    with st.chat_message("user"):
        st.markdown(user_input)

    # Stream response
    with st.chat_message("assistant"):
        try:
            response_text = st.write_stream(
                response_stream(client, system_blocks, st.session_state.messages)
            )
        except anthropic.RateLimitError:
            st.error("请求太频繁，请稍后再试。")
            st.session_state.messages.pop()
            return
        except Exception as e:
            st.error(f"出错了：{e}")
            st.session_state.messages.pop()
            return

    st.session_state.messages.append({"role": "assistant", "content": response_text})


if __name__ == "__main__":
    main()
